---
:log_level: 1
:save_rate: 1440
:debug: false
:admin: freemo
:goid_type: ":guid"
:port: 8888
:update_rate: 30
:restart_delay: 10
:address: 0.0.0.0
:intro_file: intro.txt
:start_room: 70da778a-6436-45a7-ebbb-69ffff0fea10
:restart_limit: 15
:mccp: false
:mssp: false
