---
:log_level: 0
:save_rate: 1440
:debug: false
:admin: testuser
:goid_type: ":guid"
:port: 8888
:update_rate: 30
:restart_delay: 10
:address: 0.0.0.0
:intro_file: intro.txt
:start_room: b07f3f55-a9a6-d6d3-e017-ea32ede520c8
:restart_limit: 15
:mccp: false
:mssp: false
