---
:admin: root
:address: 127.0.0.1
:port: 8080
:log_level: 2
:debug: false
:intro_file: conf/intro.txt
:save_rate: 1440
:start_room: start-room-goid-fallback
:restart_delay: 10
:restart_limit: 5
:update_rate: 30
:event_sourcing_enabled: false
:goid_type:
:mccp: false
