---
:log_level: 1
:save_rate: 1440
:debug: false
:admin: freemo
:goid_type: ":guid"
:port: 8888
:update_rate: 30
:restart_delay: 10
:address: 0.0.0.0
:intro_file: intro.txt
:start_room: 3d409184-ebea-5275-a393-104e25e7fa93
:restart_limit: 15
:mccp: false
:mssp: false
