---
:log_level: 1
:save_rate: 1440
:debug: false
:admin: freemo
:goid_type: ":guid"
:port: 8888
:update_rate: 30
:restart_delay: 10
:address: 0.0.0.0
:intro_file: intro.txt
:start_room: 603b5544-e548-41ce-00d3-0cccef297c5a
:restart_limit: 15
:mccp: false
:mssp: false
